language: node_js
node_js:
  - "14"
  - "12"
  - "10"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - aabbcc1241@yahoo.com.hk
    on_success: change
    on_failure: always
