#!/bin/bash
## gpw v0.3.0
## generate password

digits=0
method="sha256sum"
if [ "$1" == "md5" ]; then
  method="md5sum"
fi
if [ "$1" == "digits" ]; then
  digits=1
fi

echo -n "url: "; read url
if [[ $url == *"/"* ]]; then
  domain=$(echo "$url" | sed 's,/,\n,g' | grep -v "^$" | grep -v ':' | head -n 1 | sed 's,\.,\n,g' \
    | grep -Ev "^(www|com|hk|org|net|io|org)$" | xargs | sed -e 's/ /./g')
  echo -n "domain: $domain? [Y/n] "; read input
  if [ "${input,,}" = "n" ]; then
    echo -n "domain: "; read domain
  fi
else
  echo -n "domain: $url ? [Y/n] "; read input
  if [ "${input,,}" = "n" ]; then
    echo -n "domain: "; read domain
  else
    domain="$url"
  fi
fi
echo -n "seed: "; read -s seed; echo
echo -n "[confirm seed] :"; read -s seed2; echo
if [ "$seed2" != "" ] && [ "$seed" != "$seed2" ]; then
  echo "Error: seed not matched!"
  exit 1
fi
pw=$(echo "$domain$seed" | $method | sed 's/  -$//')
if [ $digits -eq 1 ]; then
  pw=$(echo "$pw" | sed 's/[a-f]//g')
fi

read -p "cut by [n] chars? " cut
if [ "$cut" != "" ]; then
  pw=$(echo "$pw" | cut --characters "1-$cut")
fi

echo "output to:"
echo "  [1] primary X selection (default)"
echo "  [2] clipboard"
echo "  [3] console"
echo -n "choice: "; read output_choice
if [ -z "$output_choice" ]; then
  output_choice="1"
fi

# ${name,,} converts the variable name to lowercase
case "${output_choice,,}" in
  "1"|"primary")
    echo "$pw" | xclip
    echo "ok: saved to primary X selection, use [middle button] or [Shift+Ins] to paste (not [Ctrl+V])"
    ;;
  "2"|"clipboard")
    echo "$pw" | xclip -sel clipboard
    echo "ok: saved to clipboard, use [Ctrl+V] to paste"
    ;;
  "3"|"console")
    echo "pw: $pw"
    ;;
  *)
    echo "invalid choice: $output_choice"
    exit 1
    ;;
esac
