= gpw

generate password for web account based on master key and service (domain) name

Hosted on link:https://gpw.surge.sh[CDN Surge]

== Supported Platforms
=== Linux
(or any other system that can run bash, e.g. windows with msys2)

`./gpw` or `bash gpw`

The password will be copied to primary X selection (not clipboard).
One can paste by [Shift+Insert] or Middle Click.

=== Web
=== Features
1. Copy to Clipboard Support
    (not enabled by default)
2. QR code generation
    (for mobile device without internet (with another computer with internet access))

==== Offline

Run the below commands to get the source code and build the bundle:
[source,bash]
----
git clone https://github.com/beenotung/gpw
cd gpw
npm install
npm run build
----
Then open *index.html* from your browser

==== Online
open link:https://gpw.surge.sh[] hosted on surge (CDN)

or link:https://ipfs.io/ipfs/Qmdvf5UK1ZJZFoto4ftqEu5EpLuNz2ej5Ei5oqCKabkuJT/[/ipfs/Qmdvf5UK1ZJZFoto4ftqEu5EpLuNz2ej5Ei5oqCKabkuJT] via ipfs.io

== Todo
1. update bash version to support length config
2. update js version to use built-in crypto module
